"""add_multi_currency

Revision ID: 2d91ed86db62
Revises: 70f117649c87
Create Date: 2026-04-15 01:08:57.142460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d91ed86db62'
down_revision: Union[str, None] = '70f117649c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('ledger_entries', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('ledger_entries', sa.Column('amount_primary', sa.Float(), nullable=True))
    op.add_column('recurring_rules', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_rules', 'currency')
    op.drop_column('ledger_entries', 'amount_primary')
    op.drop_column('ledger_entries', 'currency')
    op.drop_column('assets', 'currency')
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
