"""expand_asset_intelligence

Revision ID: 70f117649c87
Revises: 46f4a41c194e
Create Date: 2026-04-15 00:03:51.312550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f117649c87'
down_revision: Union[str, None] = '46f4a41c194e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('interest_rate', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('term_months', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('loan_start_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'accounts', ['account_id'], ['id'])
    op.add_column('ledger_entries', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ledger_entries', 'assets', ['asset_id'], ['id'])
    op.add_column('recurring_rules', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recurring_rules', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_rules', type_='foreignkey')
    op.drop_column('recurring_rules', 'asset_id')
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'asset_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'account_id')
    op.drop_column('assets', 'ticker')
    op.drop_column('assets', 'loan_start_date')
    op.drop_column('assets', 'term_months')
    op.drop_column('assets', 'interest_rate')
    # ### end Alembic commands ###
