"""Add Chart of Accounts

Revision ID: a716d148595c
Revises: e0ea92da0462
Create Date: 2026-04-14 01:52:15.657380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a716d148595c'
down_revision: Union[str, None] = 'e0ea92da0462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='categorytype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_groups_id'), 'category_groups', ['id'], unique=False)
    op.create_index(op.f('ix_category_groups_name'), 'category_groups', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['category_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('ledger_entries', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ledger_entries', 'categories', ['category_id'], ['id'])
    op.add_column('recurring_rules', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recurring_rules', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_rules', type_='foreignkey')
    op.drop_column('recurring_rules', 'category_id')
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_category_groups_name'), table_name='category_groups')
    op.drop_index(op.f('ix_category_groups_id'), table_name='category_groups')
    op.drop_table('category_groups')
    # ### end Alembic commands ###
