"""Add StatementTransaction model

Revision ID: e042d86e9c6e
Revises: 159fe9f29b46
Create Date: 2026-04-14 03:22:51.255582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e042d86e9c6e'
down_revision: Union[str, None] = '159fe9f29b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('import_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_transactions_id'), 'statement_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_statement_transactions_import_hash'), 'statement_transactions', ['import_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_transactions_import_hash'), table_name='statement_transactions')
    op.drop_index(op.f('ix_statement_transactions_id'), table_name='statement_transactions')
    op.drop_table('statement_transactions')
    # ### end Alembic commands ###
