"""Initial schema

Revision ID: e0ea92da0462
Revises: 
Create Date: 2026-04-14 01:16:11.576500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ea92da0462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.Enum('PERSONAL', 'BUSINESS', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency_type', sa.Enum('WEEKLY', 'FORTNIGHTLY', 'MONTHLY_DATE', 'ANNUAL', 'ONCE', name='frequencytype'), nullable=False),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_rules_id'), 'recurring_rules', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_rules_name'), 'recurring_rules', ['name'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROJECTED', 'ACTUAL', 'PENDING', name='ledgerstatus'), nullable=True),
    sa.Column('running_balance', sa.Float(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.Enum('PERSONAL', 'BUSINESS', name='entitytype'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recurring_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_date'), 'ledger_entries', ['date'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_date'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_recurring_rules_name'), table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_id'), table_name='recurring_rules')
    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
